context.modules = [
    {
        name = libpipewire-module-parametric-equalizer
        args = {
            equalizer.description = "Equalizer Sink"
            equalizer.filepath = "/home/bzell/.config/pipewire/autoeq/beyerdynamic.txt"
            audio.channels = 2
            audio.position = [ FL FR ]
            capture.props = {
                node.name = "input.effect.eq10"
                media.class = Audio/Sink
                filter.smart = true
                filter.smart.name = equalizer
            }
            playback.props {
                node.name = "output.effect.eq10"
                node.passive = true
                stream.dont-remix = true
            }
        }
    }
]
